name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: ["linux", "mac", "windows"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - run: docker pull debian:buster-slim
      - name: Curl Cache
        id: curl
        uses: actions/cache@v2.1.6
        with:
          path: C:\ProgramData\chocolatey\bin\curl.exe
          key: ${{ runner.os }}-curl
      - name: Install curl
        if: steps.curl.outputs.cache-hit != 'true'
        run: choco install curl --acceptlicense --confirm --verbose
        shell: cmd
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: python Install.py ${{ matrix.os }} ${{ secrets.DOCKERHUB_USERNAME }}
      - if: github.ref == 'refs/heads/master'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:${{ matrix.os }}
