name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker pull debian:buster-slim
      - uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:latest
      - uses: docker/build-push-action@v2
        if: github.ref != 'refs/heads/master'
        with:
          push: false
          tags: lordgiganticus/spcomp:latest
