name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [mac, windows, linux]

    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update
        sudo apt-get install -y wget grep unzip tar curl
    - uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - if: matrix.os == 'mac'
      shell: bash
      run: |
        export sm_url=$(wget -q -O - "http://www.sourcemod.net/downloads.php?branch=dev" | grep -oE -m1 "https://[a-z.]+/smdrop/[0-9.]+/sourcemod-(.*)-mac.zip")
        wget -q $sm_url -O sourcemod.zip
        unzip sourcemod.zip
        rm sourcemod.zip
        rm -r cfg
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:mac .
    - if: matrix.os == 'windows'
      shell: bash
      run: |
        export sm_url=$(wget -q -O - "http://www.sourcemod.net/downloads.php?branch=dev" | grep -oE -m1 "https://[a-z.]+/smdrop/[0-9.]+/sourcemod-(.*)-windows.zip")
        wget -q $sm_url -O sourcemod.zip
        unzip sourcemod.zip
        rm sourcemod.zip
        rm -r cfg
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:windows .
    - if: matrix.os == 'linux'
      run: | 
        export sm_url=$(wget -q -O - "http://www.sourcemod.net/downloads.php?branch=dev" | grep -oE -m1 "https://[a-z.]+/smdrop/[0-9.]+/sourcemod-(.*)-linux.tar.gz")
        wget -q $sm_url -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz
        rm sourcemod.tar.gz
        rm -r cfg
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:linux .
    - if: github.ref == 'refs/heads/master'
      run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/spcomp:${{ matrix.os }}"
